# guide to powerline symbols https://awesomeopensource.com/project/ryanoasis/powerline-extra-symbols
# guide to style strings https://starship.rs/advanced-config/#style-strings
# 

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$golang\
$nodejs\
$php\
$python\
$ruby\
${custom.tfenv}\
${custom.endcap}\
$line_break\
${custom.vault_token}\
${custom.vault}\
${custom.awsprofile}\
${custom.tfbackend}\
${custom.line_break}\
$jobs\
$time\
$status\
$character
"""

add_newline = false
command_timeout = 1500

[character]
error_symbol = "[ ✖](bold red) ❯"

[cmd_duration]
disabled = false

[username]
format = " $user "
disabled = false
show_always = true

[hostname]
format = " $hostname "
ssh_only = false
trim_at = ""
disabled = false

[directory]
format = " $path "
truncation_length = 3
truncate_to_repo = true
# prefix = "in "
# style = "bold cyan"
disabled = false

[git_branch]
format = " $symbol$branch"
symbol = " "

[git_commit]
format = "[\\($hash\\)](bg:#333333 $style) [\\($tag\\)](bg:#333333 $style)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]()\)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[package]
disabled = true

[golang]
symbol = " "
format = ' [$symbol$version]() '

[nodejs]
symbol = " "
format = ' [$symbol$version]() '

[python]
symbol = " "
format = ' [$symbol$version]() '

[ruby]
symbol = " "
format = ' [$symbol$version]() '

[time]
disabled = false
format = '[$time]($style)'

[custom.line_break]
command = "true"
when = '[[ "x$VAULT_ADDR$AWS_PROFILE$VAULT_TOKEN" != "x" ]] || [[ -f .terraform/terraform.tfstate ]]'
format = """[$output]()
"""

[custom.vault]
command = "echo ${VAULT_ADDR##*/}" # trim off the https://
symbol = " "
when = "[[ -n $VAULT_ADDR ]]"
format = ' $symbol$output '

[custom.awsprofile]
command = "echo $AWS_PROFILE"
symbol = " "
when = "[[ -n $AWS_PROFILE ]]"
format = ' $symbol$output '

[custom.tfbackend]
command = "jq -r .backend.config.key .terraform/terraform.tfstate"
symbol = " "
when = "[[ -f .terraform/terraform.tfstate ]]"
format = ' $symbol$output '

[custom.vault_token]
command = "echo Ⓣ"
when = "[[ -n $VAULT_TOKEN ]]"
format = '$output '

[custom.tfenv]
command = "cat /usr/local/Cellar/tfenv/2.2.2/version || cat ~/.tfenv/version"
when = "[[ -d .terraform ]]"
symbol = " "
format = ' [$symbol$output]() '

[custom.endcap]
description = "display  endcap when in a non-python/ruby/go/nodejs repo"
command = 'echo '
when = """
if git rev-parse --is-inside-work-tree; then 
  endcap=1
else 
  endcap=0
fi

(ls | egrep -q ".py$|.rb$|.js$|.go$|package.json") && endcap=0

[[ $endcap == 1 ]]
"""
format = ' $output'
