# guide to powerline symbols https://awesomeopensource.com/project/ryanoasis/powerline-extra-symbols
# guide to style strings https://starship.rs/advanced-config/#style-strings

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$golang\
$nodejs\
$php\
$python\
$ruby\
$line_break\
${custom.vault_token}\
${custom.vault}\
${custom.awsprofile}\
${custom.tfbackend}\
${custom.tfenv}\
$line_break\
$jobs\
$time\
$status\
$character
"""

# format = """
# $username\
# [\ue0b0](bg:#333333 fg:#222222)\
# $hostname\
# [\ue0b0](bg:#444444 fg:#333333)\
# $directory\
# [\ue0b0](bg:#333333 fg:#444444)\
# $git_branch\
# $git_commit\
# $git_state\
# $git_status\
# $golang\
# $nodejs\
# $php\
# $python\
# $ruby\
# ${custom.vault}\
# [\ue0b0](bg:black fg:#333333)\
# $line_break\
# ${custom.awsprofile}\
# ${custom.tfbackend}\
# $line_break\
# $jobs\
# $time\
# $status\
# $character
# """

add_newline = false
command_timeout = 1500

[character]
error_symbol = "[ ✖](bold red) ❯"

[cmd_duration]
disabled = false

[username]
format = "[ $user ](bg:#222222)"
disabled = false
show_always = true

[hostname]
format = "[ $hostname ](bg:#333333)"
ssh_only = false
trim_at = ""
disabled = false

[directory]
format = "[ $path ](bg:#444444)[$read_only](bg:#444444 $read_only_style)"
truncation_length = 3
truncate_to_repo = true
# prefix = "in "
# style = "bold cyan"
disabled = false

[git_branch]
format = "[ $symbol$branch ](bg:#333333 $style)"
symbol = " "

[git_commit]
format = "[\\($hash\\)](bg:#333333 $style) [\\($tag\\)](bg:#333333 $style)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]()\)'

[git_status]
format = '[ $all_status ]($style)'

[package]
disabled = true

[golang]
symbol = " "
format = '\[[$symbol$version]($style)\]'

[nodejs]
symbol = " "
format = '\[[$symbol$version]($style)\]'

[python]
symbol = " "
format = '\[[$symbol$version]($style)\]'

[ruby]
symbol = " "
format = '\[[$symbol$version]($style)\]'

[time]
disabled = false
format = '[$time]($style)'

[custom.vault]
command = "echo $VAULT_ADDR | cut -d/ -f3"  # shows output of command
symbol = " "
when = "[[ $VAULT_ADDR =~ vault ]]"
format = '\[[$symbol$output]()\]'

[custom.awsprofile]
command = "echo $AWS_PROFILE"
symbol = " "
when = "[[ -n $AWS_PROFILE ]]"
format = '\[[$symbol$output]()\]'

[custom.tfbackend]
command = "jq -r .backend.config.key .terraform/terraform.tfstate"
symbol = " "
when = "[[ -f .terraform/terraform.tfstate ]]"
format = '\[[$symbol$output]()\]'

[custom.vault_token]
command = "echo Ⓣ"
when = "[[ -n $VAULT_TOKEN ]]"
format = '[$symbol$output ]()'

[custom.tfenv]
command = "cat /usr/local/Cellar/tfenv/2.2.2/version || cat ~/.tfenv/version"
when = "[[ -d .terraform ]]"
symbol = "tf"
format = '\[[$symbol$output]()\]'
